block_break_delay: true # If true, after not instantly breaking a block a 6-tick delay will be applied to the player in which they can't break a block.
# Having this enabled is more true to vanilla, which also has this mechanic, but the option to disable it is here regardless.
block_recovery: true # If true, blocks will gradually recover after being damaged. If false, blocks will instantly recover after being damaged (like in vanilla)
block_recovery_delay: 60 # The delay (in ticks) until the damage on a block starts recovering
block_recovery_speed: 0.015 # The amount of health (of max 1, per tick) at which the block recovers after the delay
